# Notify (via Slack channels) when deployments begin, succeed, and/or fail.

name: CD Notify Deployment Run

on:
    workflow_run:
        workflows:
            #- Main
            - 'main.yaml'
        types:
            - completed
            - requested

jobs:
    notify:
        name: Send Notifications
        runs-on: ubuntu-latest
        steps:
          - run: cat '${{ github.event_path }}'
          - if: github.event.action == 'requested'
            run: >-
              echo 'DEPLOY_STATUS=Deploying' >> "$GITHUB_ENV"
              echo 'ICON_EMOJI=Deploying' >> "$GITHUB_ENV"
          - if: github.event.action == 'completed' && github.event.workflow_run.conclusion == 'success'
            run: >-
              echo 'DEPLOY_STATUS=:: Deployed' >> "$GITHUB_ENV"
              echo 'ICON_EMOJI=:white_check_mark:' >> "$GITHUB_ENV"
          - if: github.event.action == 'completed' && github.event.workflow_run.conclusion == 'failure'
            run: >-
              echo 'DEPLOY_STATUS=:warning: Failed to deploy' >> "$GITHUB_ENV"
              echo 'ICON_EMOJI=:warning:' >> "$GITHUB_ENV"

          - name: 'Notify #deployments'
            continue-on-error: true
            uses: pcolby/post-to-slack@v1
            with:
              channel: '#cd-test-deployments'
              icon_emoji: ${{ env.ICON_EMOJI }}
              text: >-
                <${{ github.event.workflow_run.html_url }}|${{ env.DEPLOY_STATUS }}>
                `${{ github.event.workflow_run.name }}`
              url: ${{ secrets.SLACK_WEBHOOK_URL }}

          - name: 'Notify #dev-general'
            if: >-
              github.event.action == 'completed' &&
              github.event.workflow_run.conclusion == 'failure'
            continue-on-error: true
            uses: pcolby/post-to-slack@v1
            with:
              channel: '#cd-test-dev-general'
              icon_emoji: ${{ env.ICON_EMOJI }}
              text: ${{ env.DEPLOY_STATUS }} '${{ github.event.workflow_run.name }}'
              url: ${{ secrets.SLACK_WEBHOOK_URL }}

          - name: 'Notify #general'
            if: >-
              github.event.action == 'completed' &&
              github.event.workflow.path == '.github/workflows/cd_production.yml' &&
              github.event.workflow_run.conclusion == 'success'
            continue-on-error: true
            uses: pcolby/post-to-slack@v1
            with:
              channel: '#cd-test-general'
              text: '@here Version ${{ env.RELEASE_VERSION }} is released to Production'
              url: ${{ secrets.SLACK_WEBHOOK_URL }}
