on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: pcolby/hello-world-composite-action@v1
        with:
          who-to-greet:
            foo: what if
            bar: this is
            baz: complex?
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
